### ISSUE TITLE
Unexpected API error. KeyError: com.github.brpaz.ulauncher-trello

### ISSUE THREAD

**Issue by khushman1** [brpaz/ulauncher-trello#1]
Hi,
The subject line is the exact issue that I get when I enter my trello api key and token into the preferences for the extension.

I've installed the extension from within ulauncher itself(using the url)
    [arch ~]$ node --version
    v10.6.0
    [arch ~]$ npm --version
    6.1.0

I haven't been able to trouble shoot this. Any help would be appreciated :)

Update: I've noticed on other extensions that this error often occurs due to missing commands/libraries. Are their any other requirements?

**Comment by LiljebergXYZ** [comment]
@khushman1 I experienced this issue as well and finally figured it out, you have to install `trello` through `pip` and then restart ulauncher :smiley:

**Comment by VladChekunov** [comment]
Also, you must reinstall _ulauncher-trello_ via _Ulauncher_ after installing _trello_ via _pip_.
